name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: 'always'
  RUSTFLAGS: '-D warnings'

jobs:
  test-stable:
    name: Test stable
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # Linux
          - runs-on: ubuntu-latest
          # Windows
          - runs-on: windows-latest
          # MacOS
          - runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.76.0
      - run: cargo test -- --skip args::args_tests::update_config_test_color_choice::case_4 --skip test_package

  clippy:
    name: Check that clippy is happy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.76.0
        components: clippy
    - run: cargo clippy --workspace --all-features --all-targets --no-deps -- -D warnings

  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.76.0
        components: rustfmt
    - run: cargo fmt --all -- --check
